### ISSUE TITLE
Add some sort of ical support on schedule

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#120]

**Comment by patrick91** [comment]
do we want to publish all the session on a calendar or allow users to build their own calendar?

**Comment by Vaibhavs10** [comment]
One session at a time with the option that the calendar invite updates automatically in case room details or session timings are updated. 

Nobody attends all the sessions especially those happening at the same time ;) and there's realistically no point for anyone to have all the sessions on their phone, except ofc to create an overly messy calendar

**Comment by patrick91** [comment]
Let's add a button like pyfest.online for this year :)
