### ISSUE TITLE
Bug: Unable to see Text written on How to apply button.

### ISSUE THREAD

**Issue by giyednap** [EuroPython/website#20]
In EuroPython Website, [Financial Aid Column](https://ep2022.europython.eu/finaid) The Text written on the Button which re-directs to Google Form, is hidden but It is visible on hover, Here is Snapshot to the Issue:
<img width="809" alt="Screenshot 2022-03-15 at 5 44 18 PM" src="https://user-images.githubusercontent.com/78334545/158376672-62562b13-f968-457e-9fdf-7427cbdc36b7.png">

Thanks, Gaurav!

**Comment by patrick91** [comment]
Hi @giyednap! Thanks for the report! this was fixed by @artcz earlier 😊
