### ISSUE TITLE
Expired HTTPS certificate

### ISSUE THREAD

**Issue by hugovk** [EuroPython/website#215]
The HTTPS certificate expired on Sunday 27 November 2022 for at least:

* https://blog.europython.eu/
* https://www.europython-society.org/
* https://ep2021.europython.eu/
* https://ep2020.europython.eu/
* https://ep2019.europython.eu/
* https://secure.europython.eu/

<img width="538" alt="image" src="https://user-images.githubusercontent.com/1324225/204216449-1fd2d335-90ba-48e0-ad56-5b9a14c356d8.png">

Still working, because it has its own instead of using `secure.europython.eu`:

* https://ep2022.europython.eu/

<img width="533" alt="image" src="https://user-images.githubusercontent.com/1324225/204216860-986a5170-b39f-4d5a-b734-7edbdedf83b2.png">

**Comment by artcz** [comment]
Hi @hugovk 

This is fixed now, thanks for reporting!

Cheers
