### ISSUE TITLE
Anchor links for headers don't jump to the relevant header

### ISSUE THREAD

**Issue by SebastiaanZ** [EuroPython/website#237]
If you add a markdown header to a "pages-content" file, the Next.JS rendering will automatically wrap the header in a link with an anchor for that header (e.g., [https://ep2023.europython.eu/mentorship#mentee][mentee-anchor] for the header "Mentee" on the mentorship page). The problem is that the target anchor name isn't added as the `id` attribute of the header HTML tag.

This means that anchor links don't actually jump to the relevant location on the page.

[mentee-anchor]: https://ep2023.europython.eu/mentorship#2-workshops

**Comment by SebastiaanZ** [comment]
The same goes for a markdown footnote. The footnote will be rendered correctly, with an anchor link at the place of the footnote reference to the footnote, but the footnote itself (rendered at the bottom) will not have the necessary `id` to make the footnote link work.

**Comment by SebastiaanZ** [comment]
> @SebastiaanZ I fixed the headings :)
> 
> do know where we are using footnotes? I'll fix them as well :)

@patrick91 There's one on the new finaid page, `/finaid`.

**Comment by patrick91** [comment]
@SebastiaanZ fixed in ae99a41! thanks 😊
