### ISSUE TITLE
Community voting is closed but the voting.europython.eu is open

### ISSUE THREAD

**Issue by hugovk** [EuroPython/website#284]
I just saw that community voting closed on 14th April:

https://fosstodon.org/@europython/110190566061335730

And https://ep2023.europython.eu/voting confirms it has closed.

But https://voting.europython.eu bookmarked is still accepting votes. I was still voting on a few every day for the last three weeks despite it being officially "closed" 🙃 

Please could you actually close https://voting.europython.eu and add text at the top?

**Comment by artcz** [comment]
Hi @hugovk!

We changed it to readonly now and we're planning to shut it down completely in a near future.

While you technically could still vote (and can still see how you voted), the results that were used for the purpose of the programme selection are from April 14th, when the voting officially finished.

Thanks for reporting!
