### ISSUE TITLE
Some entries on the list of sessions are duplicated

### ISSUE THREAD

**Issue by artcz** [EuroPython/website#300]
To be investigated :D

Some extra context already passed on discord, but for example Sebastiaan's talk and Sanskar's tutorial appear twice on the list. There about ten or so duplicates in total.

**Comment by patrick91** [comment]
I'm removing the duplicates manually for now :)

**Comment by patrick91** [comment]
This was/is a bug of the pagination in pretalx, we did a workaround, so I'll close this for now :)
