### ISSUE TITLE
missing tutorial in list of sessions

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#303]
“Practical tools for documentation at scale” by Daniele Procida is not listed on /sessions or /tutorials

**Comment by patrick91** [comment]
should be good now, I forgot to make that page revalidate every 5 minutes :)

**Comment by hypha** [comment]
Hey @patrick91 still don't see this tutorial. Could you double check?

**Comment by hypha** [comment]
The issue has now been resolved in https://github.com/EuroPython/website/commit/6b6132b2fab067827759e658d6861b9c7e35d3e7. 

The issue mainly to do with pretalx api side. When you set a limit smaller than total results, the pretalx API  paginates most lists of object. Due to the lack of stable sorting, some results return in both page 1, and page 2, cutting off all the actual results that pass the total count threshold. We have set the limit to be bigger than the total sessions for now to avoid pagination, returning all results correctly.
