### ISSUE TITLE
[Feature Request] additions to the schedule

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#306]
- [x] 4 tutorial tracks are accessible to tutorial & combined tickets holders. But we have one track for people with a conference tickets, and the other open to public (both requires additional registration on their dedicated event page).  It'd be really nice to have a way to mark the differences on the schedule - perhaps putting a thicker grid between the normal tracks and special tracks and add "registration advised/required" to the special tracks. 
- [x]  We have some reserved slots for the open space, e.g. Mentored Sprints. We'll list the events on the menu /events. But would be good to have these represented on the schedule (could be a tab called Open Space). 
- [x] Would be good to list the sprints on the schedule (rooms, coffee break) - perhaps show a dropdown on the schedule but redirect to the sprint page.

**Comment by patrick91** [comment]
I feel like we could experiment on some of these together on call (with others too), but let me put down some ideas:

>  4 tutorial tracks are accessible to tutorial & combined tickets holders. But we have one track for people with a conference tickets, and the other open to public (both requires additional registration on their dedicated event page). It'd be really nice to have a way to mark the differences on the schedule.

The ones we registration can have a "register here" button on the schedule item, for the other we can have some labels maybe?

For PyCon Italia we do this for workshops:

<img width="332" alt="CleanShot 2023-05-19 at 11 06 15@2x" src="https://github.com/EuroPython/website/assets/667029/30809eac-4398-4b65-b007-7a9bef474911">

>  We have some reserved slots for the open space, e.g. Mentored Sprints. We'll list the events on the menu /events. But would be good to have these represented on the schedule (could be a tab called Open Space).

sure, do we have many open spaces running at once? (like PyCon US: http://pycon.us/os)


>  Would be good to list the sprints on the schedule (rooms, coffee break.

Sounds easy enough 😊

**Comment by hypha** [comment]
For the sprints, I think we could still have the dropdown displayed on the schedule, but then we can redirect to /sprints and we list the breaks, lunch and room directly as a simple table on the sprint page. This way, all sprints stay in one place but people who go to the schedule can still find sprints info.

**Comment by hypha** [comment]
all implemented in https://github.com/EuroPython/website/pull/330
