### ISSUE TITLE
[UX] consider having shorter length per line

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#343]
I briefly looked into sources on the effect of line length on readability for digital screens. Unfortunately, I don't have access to most full-text articles anymore.

There seem to be a couple of different approaches to this question, though. Those approaches include measuring a speed/comprehension trade-off, testing for scanning/visual search in text, and measuring subjective preferences for line lengths. The problem is that there seem to be different answers based on what is measured.

In general, I've read that:

- Longer line lengths are better for quick scanning, as you have to scroll less and make fewer line jumps. 
- Medium line lengths (often defined as somewhere between 50 - 80 characters per line) are better for accuracy 
- Medium line lengths are preferred by most participants.

Here ar a few sources:

### Dyson, M.C., & Kipping, G.J. (1998). The Effects of Line Length and Method of Movement on Patterns of Reading from Screen. Visible Language, 32.

This study comes to two different conclusions:

- People read faster at long line lengths (defined as 100 characters per line) compared to shorter line lengths while reading comprehension stayed pretty much constant over line lengths
- People subjectively preferred reading at medium line lengths (with the most preferred length being 55 characters per line)

In the discussion, they suggest that you should be careful applying principles from printed text to text on screens.

### Ling, J., & Van Schaik, P. (2006). The influence of font type and line length on visual search and information retrieval in web pages. International journal of human-computer studies, 64(5), 395-404.

This study comes to the conclusion that longer lines allow for faster scanning of a text for specific terms, but when it comes to processing the information and recalling it later, they found an optimal line length of 70 characters per line. In addition, the subjective preference was for shorter line lengths (55 - 70 characters per line), with a strong effect size in their first experiment and a small-to-medium effect size in their second experiment.

Their main design recommendation relevant to our discussion is:

> Given a choice between using long (85–100) and short line lengths (55–70), designers should opt for the latter, because although scanning web pages is also a major activity when finding information on websites (Kitajima et al., 2000), the majority of textual web content is presented to be read rather than skimmed. (page 403)

### Baymard Institute

This is a private institute from Denmark, but they do a lot of applied UX research. They have an [article on line length](https://baymard.com/blog/line-length-readability) that recommends 50-75 characters per line.

### Wikipedia

Wikipedia does not provide a clear guideline in terms of line length for electronic text, but also states that shorter line lengths are better for accuracy, while longer line length have benefits for scanning tasks. See https://en.wikipedia.org/wiki/Line_length.

_Originally posted by @SebastiaanZ in https://github.com/EuroPython/website/issues/224#issuecomment-1447802859_

**Comment by patrick91** [comment]
do you have an example of where we have long lines?

**Comment by hypha** [comment]
@patrick91 @SebastiaanZ's comment was in relation to 2022's line length on content page, vs 2023's. We have longer lines this year. 
![image](https://github.com/EuroPython/website/assets/6319134/361cf5b6-5bed-42d6-9056-79171a5d491f)
![image](https://github.com/EuroPython/website/assets/6319134/f56713dd-84eb-415a-a09b-d6bd7645017a)

**Comment by patrick91** [comment]
this is done!
