### ISSUE TITLE
[UX] Mark tutorial days on schedule days dropdown

### ISSUE THREAD

**Issue by gbdlin** [EuroPython/website#347]
Right now the default day is the first tutorial day. It is not clear we're looking at tutorials and not at talks and it may be very confusing for users. Adding some mark in the dropdown, like it is present right now for sprints, should improve that.

**Comment by patrick91** [comment]
@artcz do you know if in pretalx we can add metadata to days? otherwise I can hard code this :)

**Comment by patrick91** [comment]
this is done! (hard coded for now)
