### ISSUE TITLE
Add date/time/room to session pages

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [EuroPython/website#364]
I think it would be _tremendously_ beneficial if session pages (e.g., talk/tutorial/poster session pages) included the date, time, and the room in which the session is taking place.

**Comment by hypha** [comment]
I think @patrick91 has the plan to do that. When that's implemented, related is this: https://github.com/EuroPython/website/issues/222

**Comment by patrick91** [comment]
this is done :)

**Comment by rodrigogiraoserrao** [comment]
Awesome!
