### ISSUE TITLE
List speaker sessions in speaker page

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [EuroPython/website#365]
It would be a nice thing to have a list of all the speaker sessions in the speaker page; i.e., each speaker page could link to all of that speaker's sessions.

Example from the 2021 website: https://ep2021.europython.eu/profiles/rodrigo-girao-serrao/

**Comment by patrick91** [comment]
done!

**Comment by rodrigogiraoserrao** [comment]
Let's go! 🚀
