### ISSUE TITLE
Resources uploaded to pretalx should show on individual sessions 

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#375]
Since we are using resources on pretalx, where speakers can upload their slides (super useful stuff!), we should list them on the website.

**Comment by patrick91** [comment]
<img width="1200" alt="CleanShot 2023-07-26 at 10 03 22@2x" src="https://github.com/EuroPython/website/assets/667029/7ffd300a-e312-4ff9-9693-9f3704bfc1ec">

note for myself

**Comment by egeakman** [comment]
@patrick91 We can serve this URL at the [``programapi``](https://github.com/EuroPython/programapi), if that would make things easier! 😊
