### ISSUE TITLE
Texts do not fit the screen on mobile

### ISSUE THREAD

**Issue by egeakman** [EuroPython/website#527]
Here are two examples:

![Screenshot_20240321-121118_Chrome.png](https://github.com/EuroPython/website/assets/75242929/7b55d3ab-ed9d-4e22-9bdd-751093ae0ddb)

![Screenshot_20240321-124017_Chrome.png](https://github.com/EuroPython/website/assets/75242929/ff0efb7b-2864-4e3a-8461-6dd8af68511c)

I'm using Chrome in Android.

I'm not sure if these kind of issues are a priority or not, so just opening one just in case :)

**Comment by patrick91** [comment]
@egeakman thanks! I'll go and make the fonts smaller on mobile 😊

**Comment by patrick91** [comment]
@egeakman could you check it here? https://ep2024-git-fix-mobile-europython-society.vercel.app?_vercel_share=hjT4n2YJw1VnvjAStt2bnskfXhH71kLR

**Comment by egeakman** [comment]
It looks like this:

![Screenshot_20240321-130539_Chrome.png](https://github.com/EuroPython/website/assets/75242929/712ca379-091f-4fec-a2b0-f404b2d4dcb3)

![Screenshot_20240321-130524_Chrome.png](https://github.com/EuroPython/website/assets/75242929/01bd9a11-dcc4-4ab7-9c88-878d089daa10)

![Screenshot_20240321-130531_Chrome.png](https://github.com/EuroPython/website/assets/75242929/8871121b-2e9a-433b-8bf9-d73e01f29d9a)

**Comment by patrick91** [comment]
that looks good to me! I'll merge 😊

thanks!
