### ISSUE TITLE
EuroPython Society website links to EuroPython 2023

### ISSUE THREAD

**Issue by hugovk** [EuroPython/website#555]
There's a link in the top banner of https://europython-society.org/ for "[📢 EuroPython 2023](https://ep2023.europython.eu/)" which should be updated to "[📢 EuroPython 2024](https://ep2024.europython.eu/)".

Please could you update it?

**Comment by Vaibhavs10** [comment]
Hi Hugo! We just updated it, thanks a ton for the suggestion! 🤗

**Comment by hugovk** [comment]
Thanks!
