### ISSUE TITLE
https://ep2024.europython.eu/keynoters on Homepage 404

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#611]
The Keynote Speakers heading on the homepage points to https://ep2024.europython.eu/keynoters  which is currently 404.
![image](https://github.com/EuroPython/website/assets/6319134/d8154b98-4298-4fff-9858-37ea33fa38fe)

**Comment by egeakman** [comment]
src/content/pages/keynoters.mdx:

```mdx
---
title: Keynoters
subtitle: Keynoters
---

import Keynoters from "../../components/keynoters/keynoters.astro";

<Keynoters />
```

Something as simple as that may work as a base. Though I'm not familiar with Astro, and we may want to do something else here.

![image](https://github.com/EuroPython/website/assets/75242929/ed9ef4f2-ecd1-4d6c-91c0-c87586f60f70)
