### ISSUE TITLE
The schedule does not follow a meaningful sequence for tab traversal

### ISSUE THREAD

**Issue by ADubhlaoich** [EuroPython/website#695]
## Description
**As an** attendee, **I want** the schedule to follow a meaningful sequence, **so that** tab traversal is sensible.

## Acceptance criteria
A user should be able to navigate through the entirety of the schedule with a keyboard alone.

Within the context of the schedule, this means that the tab order should go left to right, then top to bottom.

## Additional information
[WCAG 1.3.2 Meaningful Sequence](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence)
[WCAG 2.1 Keyboard Accessible](https://www.w3.org/WAI/WCAG21/Understanding/keyboard-accessible)
[WCAG 2.4.3 Focus Order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html)

**Comment by ADubhlaoich** [comment]
The schedule tab order is incoherent. 

In a left to right order, the expectation would be to traverse across the clubs of the schedule, then down the timeslots.

Taking the clubs as columns (A-H) and the time slots as rows (1+), the initial part of the schedule goes as follows:

- 1A
- 2C
- 2A
- 2B
- 2H
- 2D
- 2E
- 3C
- 3A
- 3B
- 3H
- 3D
- 3E

The fact there's a discernible pattern suggests it might be something easily fixed in how the schedule is generated.

I also don't understand why it jumps from E to H without F or G.

**Comment by patrick91** [comment]
@ADubhlaoich this should be fixed now, can you double check? (and thanks for the report!)

**Comment by ADubhlaoich** [comment]
Yup, looks good!
