### ISSUE TITLE
The secondary colour used for backgrounds has poor contrast with the inverted body text

### ISSUE THREAD

**Issue by ADubhlaoich** [EuroPython/website#702]
## Description
**As an** attendee, **I want** the website text to have good contrast, **so that** it's easy for me to read information.

## Acceptance criteria
The current secondary colour (pink) used in buttons has a contrast ratio of 2.2 with the inverted body text (white).

One of the two should be changed for the sake of better visibility and readability.

## Additional information
[WCAG 1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)

**Comment by ADubhlaoich** [comment]
Unfortunately because this is small text it requires a minimum ratio of 4.5: if it was used for large text a ratio of 3 would be acceptable.

The closest colour which fulfils the contrast ratio requirement is #C74C69.

This is the kind of thing that needs to be thought of at the design stages.

This may affect other buttons, but the impact of changing the white is a much bigger headache to fix.

**Comment by ADubhlaoich** [comment]
I'm trying to make issues as discrete as possible but it would get ridiculous if I did it on a colour by colour basis.

The button colour should be shifted to #EC130E for better ratio (It's 3.9, the new colour is 4.5).

The button (hover) colour is fine.

**Comment by hugovk** [comment]
See PR https://github.com/EuroPython/website/pull/774 which replaces the pink `bg-secondary` with red `bg-button` for the buttons in the cards on the frontpage.

**Comment by ADubhlaoich** [comment]
Resolved in above PR: I anticipate this type of issue could become a problem in the future, but can be avoided by having the accessibility workgroup involved in the early stages of design.
