### ISSUE TITLE
CoC button does not show on mobile

### ISSUE THREAD

**Issue by hypha** [EuroPython/website#83]
![image](https://user-images.githubusercontent.com/6319134/171892264-571b0643-e1cd-4ed8-b49d-420da15a0a20.png)

**Comment by patrick91** [comment]
would it be fine to have it in the menu? It won't fit with the buy tickets link being there

**Comment by hypha** [comment]
> would it be fine to have it in the menu? It won't fit with the buy tickets link being there

Yes, I think that would work!
