### ISSUE TITLE
Sprints page cut off on mobile

### ISSUE THREAD

**Issue by hugovk** [EuroPython/website#847]
https://ep2024.europython.eu/sprints

![Screenshot_2024-07-12-16-10-21-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/649331cb-a46c-43f2-b63b-81124c6ae237)

**Comment by egeakman** [comment]
Thanks for the report Hugo! We unfortunately have this issue on most of our MDX pages. We have an issue open for it: #700

I'll close this to track the issue over there 🙂
