### ISSUE TITLE
In-Complete information on FAQ page.

### ISSUE THREAD

**Issue by yednapg** [EuroPython/website#97]
<img width="1111" alt="Screenshot 2022-06-14 at 12 54 38 PM" src="https://user-images.githubusercontent.com/103869798/173518550-d75d056c-76f6-431a-a164-db193c1c2936.png">
<img width="1111" alt="Screenshot 2022-06-14 at 12 54 56 PM" src="https://user-images.githubusercontent.com/103869798/173518568-c9f100e0-25d4-42b2-87ab-7fe47b95efc9.png">

**Comment by hypha** [comment]
Hi @yednapg many thanks for reporting! fixed it in https://github.com/EuroPython/website/pull/98
